name = "MultiPrecisionArrays"
uuid = "e0585029-f0fd-471c-997a-b805c9f71f28"
authors = ["C. T. (Tim) Kelley <tim_kelley@ncsu.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
SIAMFANLEquations = "084e46ad-d928-497d-ad5e-07fa361a48c4"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Polyester = "0.7"
SIAMFANLEquations = "1"
julia = "1"
LinearAlgebra="1"
SparseArrays="1"
